/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.scientificcalculator;

import javax.swing.JOptionPane;

/**
 *
 * @author tfbd
 */
public class ScientificCalc extends javax.swing.JFrame {

    /**
     * Creates new form ScientificCalc
     */
    public ScientificCalc() {
        initComponents();
        jRadioButtonForON.setEnabled(false);
    }
    
    double num1, num2, result;
    String opr;
    
    public void enable()
    {
        jTextField1.setEnabled(true);
        
        jRadioButtonForON.setEnabled(false);
        jRadioButtonForOFF.setEnabled(true);
        
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButtonForROOT.setEnabled(true);
        jButton4.setEnabled(true);
        jButtonForSQUARE.setEnabled(true);
        jButtonForCUBE.setEnabled(true);
        jButtonForTAN.setEnabled(true);
        jButtonForSIN.setEnabled(true);
        jButton9.setEnabled(true);
        jButtonForCOS.setEnabled(true);
        jButtonForTANH.setEnabled(true);
        jButtonForSINH.setEnabled(true);
        jButtonForMODULAS.setEnabled(true);
        jButtonForCOSH.setEnabled(true);
        jButtonForBACK.setEnabled(true);
        jButtonForLOG.setEnabled(true);
        jButtonForCLR.setEnabled(true);
        jButtonForPLUS.setEnabled(true);
        jButtonFor9.setEnabled(true);
        jButtonFor8.setEnabled(true);
        jButtonFor7.setEnabled(true);
        jButtonForMINUS.setEnabled(true);
        jButtonFor6.setEnabled(true);
        jButtonFor5.setEnabled(true);
        jButtonFor4.setEnabled(true);
        jButtonFor4.setEnabled(true);
        jButtonForMULTIPICATION.setEnabled(true);
        jButtonForEQUAL.setEnabled(true);
        jButtonForDOT.setEnabled(true);
        jButtonFor0.setEnabled(true);
        jButtonFor3.setEnabled(true);
        jButtonFor2.setEnabled(true);
        jButtonFor1.setEnabled(true);
        jButtonForDIVISION.setEnabled(true);
        jButtonForFACTORIAL.setEnabled(true);
        
    }
    
    
     public void disable()
    {
        jTextField1.setEnabled(false);
        
        jRadioButtonForON.setEnabled(true);
        jRadioButtonForOFF.setEnabled(false);
        
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButtonForROOT.setEnabled(false);
        jButton4.setEnabled(false);
        jButtonForSQUARE.setEnabled(false);
        jButtonForCUBE.setEnabled(false);
        jButtonForTAN.setEnabled(false);
        jButtonForSIN.setEnabled(false);
        jButton9.setEnabled(false);
        jButtonForCOS.setEnabled(false);
        jButtonForTANH.setEnabled(false);
        jButtonForSINH.setEnabled(false);
        jButtonForMODULAS.setEnabled(false);
        jButtonForCOSH.setEnabled(false);
        jButtonForBACK.setEnabled(false);
        jButtonForLOG.setEnabled(false);
        jButtonForCLR.setEnabled(false);
        jButtonForPLUS.setEnabled(false);
        jButtonFor9.setEnabled(false);
        jButtonFor8.setEnabled(false);
        jButtonFor7.setEnabled(false);
        jButtonForMINUS.setEnabled(false);
        jButtonFor6.setEnabled(false);
        jButtonFor5.setEnabled(false);
        jButtonFor4.setEnabled(false);
        jButtonFor4.setEnabled(false);
        jButtonForMULTIPICATION.setEnabled(false);
        jButtonForEQUAL.setEnabled(false);
        jButtonForDOT.setEnabled(false);
        jButtonFor0.setEnabled(false);
        jButtonFor3.setEnabled(false);
        jButtonFor2.setEnabled(false);
        jButtonFor1.setEnabled(false);
        jButtonForDIVISION.setEnabled(false);
        jButtonForFACTORIAL.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButtonForON = new javax.swing.JRadioButton();
        jRadioButtonForOFF = new javax.swing.JRadioButton();
        jButtonForPLUS = new javax.swing.JButton();
        jButtonFor9 = new javax.swing.JButton();
        jButtonFor8 = new javax.swing.JButton();
        jButtonFor7 = new javax.swing.JButton();
        jButtonForMINUS = new javax.swing.JButton();
        jButtonFor6 = new javax.swing.JButton();
        jButtonFor5 = new javax.swing.JButton();
        jButtonFor4 = new javax.swing.JButton();
        jButtonForMULTIPICATION = new javax.swing.JButton();
        jButtonForEQUAL = new javax.swing.JButton();
        jButtonForCUBE = new javax.swing.JButton();
        jButtonForDOT = new javax.swing.JButton();
        jButtonForTAN = new javax.swing.JButton();
        jButtonFor0 = new javax.swing.JButton();
        jButtonForSIN = new javax.swing.JButton();
        jButtonFor3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonFor2 = new javax.swing.JButton();
        jButtonForCOS = new javax.swing.JButton();
        jButtonFor1 = new javax.swing.JButton();
        jButtonForTANH = new javax.swing.JButton();
        jButtonForDIVISION = new javax.swing.JButton();
        jButtonForSINH = new javax.swing.JButton();
        jButtonForFACTORIAL = new javax.swing.JButton();
        jButtonForMODULAS = new javax.swing.JButton();
        jButtonForCOSH = new javax.swing.JButton();
        jButtonForBACK = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonForROOT = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonForSQUARE = new javax.swing.JButton();
        jButtonForLOG = new javax.swing.JButton();
        jButtonForCLR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scientific Calculator");
        setBackground(new java.awt.Color(102, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(117, 208, 244));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonGroup1.add(jRadioButtonForON);
        jRadioButtonForON.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonForON.setText("ON");
        jRadioButtonForON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonForONActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonForOFF);
        jRadioButtonForOFF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonForOFF.setText("OFF");
        jRadioButtonForOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonForOFFActionPerformed(evt);
            }
        });

        jButtonForPLUS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonForPLUS.setText("+");
        jButtonForPLUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForPLUSActionPerformed(evt);
            }
        });

        jButtonFor9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFor9.setText("9");
        jButtonFor9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFor9ActionPerformed(evt);
            }
        });

        jButtonFor8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFor8.setText("8");
        jButtonFor8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFor8ActionPerformed(evt);
            }
        });

        jButtonFor7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFor7.setText("7");
        jButtonFor7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFor7ActionPerformed(evt);
            }
        });

        jButtonForMINUS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonForMINUS.setText("-");
        jButtonForMINUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForMINUSActionPerformed(evt);
            }
        });

        jButtonFor6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFor6.setText("6");
        jButtonFor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFor6ActionPerformed(evt);
            }
        });

        jButtonFor5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFor5.setText("5");
        jButtonFor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFor5ActionPerformed(evt);
            }
        });

        jButtonFor4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFor4.setText("4");
        jButtonFor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFor4ActionPerformed(evt);
            }
        });

        jButtonForMULTIPICATION.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonForMULTIPICATION.setText("*");
        jButtonForMULTIPICATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForMULTIPICATIONActionPerformed(evt);
            }
        });

        jButtonForEQUAL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonForEQUAL.setText("=");
        jButtonForEQUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForEQUALActionPerformed(evt);
            }
        });

        jButtonForCUBE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonForCUBE.setText("x^3");
        jButtonForCUBE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForCUBEActionPerformed(evt);
            }
        });

        jButtonForDOT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonForDOT.setText(".");
        jButtonForDOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForDOTActionPerformed(evt);
            }
        });

        jButtonForTAN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonForTAN.setText("tan");
        jButtonForTAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForTANActionPerformed(evt);
            }
        });

        jButtonFor0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFor0.setText("0");
        jButtonFor0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFor0ActionPerformed(evt);
            }
        });

        jButtonForSIN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonForSIN.setText("sin");
        jButtonForSIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForSINActionPerformed(evt);
            }
        });

        jButtonFor3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFor3.setText("3");
        jButtonFor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFor3ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setText("exp");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButtonFor2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFor2.setText("2");
        jButtonFor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFor2ActionPerformed(evt);
            }
        });

        jButtonForCOS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonForCOS.setText("cos");
        jButtonForCOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForCOSActionPerformed(evt);
            }
        });

        jButtonFor1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFor1.setText("1");
        jButtonFor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFor1ActionPerformed(evt);
            }
        });

        jButtonForTANH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonForTANH.setText("tanh");
        jButtonForTANH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForTANHActionPerformed(evt);
            }
        });

        jButtonForDIVISION.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonForDIVISION.setText("/");
        jButtonForDIVISION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForDIVISIONActionPerformed(evt);
            }
        });

        jButtonForSINH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonForSINH.setText("sinh");
        jButtonForSINH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForSINHActionPerformed(evt);
            }
        });

        jButtonForFACTORIAL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonForFACTORIAL.setText("n!");
        jButtonForFACTORIAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForFACTORIALActionPerformed(evt);
            }
        });

        jButtonForMODULAS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonForMODULAS.setText("%");
        jButtonForMODULAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForMODULASActionPerformed(evt);
            }
        });

        jButtonForCOSH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonForCOSH.setText("cosh");
        jButtonForCOSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForCOSHActionPerformed(evt);
            }
        });

        jButtonForBACK.setBackground(new java.awt.Color(255, 102, 51));
        jButtonForBACK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonForBACK.setText("B");
        jButtonForBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForBACKActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("x^y");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("1/x");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonForROOT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonForROOT.setText("R");
        jButtonForROOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForROOTActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("+/-");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButtonForSQUARE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonForSQUARE.setText("x^2");
        jButtonForSQUARE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForSQUAREActionPerformed(evt);
            }
        });

        jButtonForLOG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonForLOG.setText("log");
        jButtonForLOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForLOGActionPerformed(evt);
            }
        });

        jButtonForCLR.setBackground(new java.awt.Color(255, 102, 51));
        jButtonForCLR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonForCLR.setText("clr");
        jButtonForCLR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForCLRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonForROOT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonForMODULAS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonForCLR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonForBACK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonForPLUS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonForSIN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonForCOS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonForTAN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonForLOG, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jButtonForSINH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonForCOSH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonForTANH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonFor0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonForDOT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonForEQUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonForCUBE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonFor7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonFor8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonFor9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonForMINUS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonForFACTORIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonFor1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonFor2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonFor3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonForDIVISION, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonForON)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonForOFF))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonForSQUARE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonFor4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonFor5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonFor6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonForMULTIPICATION, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonForOFF)
                    .addComponent(jRadioButtonForON))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonForROOT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForSIN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForCOS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForTAN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonForSINH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonForCOSH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonForTANH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonForLOG, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForMODULAS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForCLR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForBACK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForPLUS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFor7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFor8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFor9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForMINUS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForCUBE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFor4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFor5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFor6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForMULTIPICATION, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForSQUARE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFor1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFor2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFor3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForDIVISION, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForFACTORIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonForEQUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonForDOT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFor0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonForCLRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForCLRActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_jButtonForCLRActionPerformed

    private void jButtonForLOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForLOGActionPerformed
        double t = Math.log(Double.parseDouble(jTextField1.getText()));

        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonForLOGActionPerformed

    private void jButtonForSQUAREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForSQUAREActionPerformed
        double t = Double.parseDouble(jTextField1.getText());

        t = t*t;
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonForSQUAREActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        double t = Double.parseDouble(String.valueOf(jTextField1.getText()));

        t = t*(-1);
        jTextField1.setText(String.valueOf(t));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonForROOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForROOTActionPerformed
        double t = Math.sqrt(Double.parseDouble(jTextField1.getText()));

        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonForROOTActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double t =1/(Double.parseDouble(jTextField1.getText()));

        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());

        jTextField1.setText("");
        opr = "x^y";
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButtonForOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonForOFFActionPerformed
        disable();
        
        if (jRadioButtonForOFF == jRadioButtonForOFF)
        {
            JOptionPane.showMessageDialog(null, "Thanks for using ('~')");
            jFrame obj = new jFrame();
            obj.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButtonForOFFActionPerformed

    private void jRadioButtonForONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonForONActionPerformed
        enable();
        
        if(jRadioButtonForON == jRadioButtonForON)
        {
            JOptionPane.showMessageDialog(null, " Welcome ");
            jFrame obj = new jFrame();
            obj.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButtonForONActionPerformed

    private void jButtonForBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForBACKActionPerformed
        String backSpace = null;

        if(jTextField1.getText().length() > 0 )
        {
            StringBuilder s = new StringBuilder(jTextField1.getText());
            s.deleteCharAt(jTextField1.getText().length() - 1);
            backSpace = s.toString();
            jTextField1.setText(backSpace);
        }
    }//GEN-LAST:event_jButtonForBACKActionPerformed

    private void jButtonForCOSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForCOSHActionPerformed
        double t = Math.cosh(Double.parseDouble(jTextField1.getText()));

        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonForCOSHActionPerformed

    private void jButtonForMODULASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForMODULASActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());

        jTextField1.setText("");
        opr = "%";
    }//GEN-LAST:event_jButtonForMODULASActionPerformed

    private void jButtonForFACTORIALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForFACTORIALActionPerformed
        double t = Double.parseDouble(jTextField1.getText());

        double fact = 1;
        while(t!=0)
        {
            fact = fact*t;
            t--;
        }
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + fact);
    }//GEN-LAST:event_jButtonForFACTORIALActionPerformed

    private void jButtonForSINHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForSINHActionPerformed
        double t = Math.sinh(Double.parseDouble(jTextField1.getText()));

        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonForSINHActionPerformed

    private void jButtonForDIVISIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForDIVISIONActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());

        jTextField1.setText("");
        opr = "/";
    }//GEN-LAST:event_jButtonForDIVISIONActionPerformed

    private void jButtonForTANHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForTANHActionPerformed
        double t = Math.tanh(Double.parseDouble(jTextField1.getText()));

        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonForTANHActionPerformed

    private void jButtonFor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFor1ActionPerformed
        jTextField1.setText(jTextField1.getText() + "1");
    }//GEN-LAST:event_jButtonFor1ActionPerformed

    private void jButtonForCOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForCOSActionPerformed
        double t = Math.cos(Double.parseDouble(jTextField1.getText()));

        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonForCOSActionPerformed

    private void jButtonFor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFor2ActionPerformed
        jTextField1.setText(jTextField1.getText() + "2");
    }//GEN-LAST:event_jButtonFor2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        double t = Math.exp(Double.parseDouble(jTextField1.getText()));

        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonFor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFor3ActionPerformed
        jTextField1.setText(jTextField1.getText() + "3");
    }//GEN-LAST:event_jButtonFor3ActionPerformed

    private void jButtonForSINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForSINActionPerformed
        double t = Math.sin(Double.parseDouble(jTextField1.getText()));

        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonForSINActionPerformed

    private void jButtonFor0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFor0ActionPerformed
        jTextField1.setText(jTextField1.getText() + "0");
    }//GEN-LAST:event_jButtonFor0ActionPerformed

    private void jButtonForTANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForTANActionPerformed
        double t = Math.tan(Double.parseDouble(jTextField1.getText()));

        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonForTANActionPerformed

    private void jButtonForDOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForDOTActionPerformed
        jTextField1.setText(jTextField1.getText() + ".");
    }//GEN-LAST:event_jButtonForDOTActionPerformed

    private void jButtonForCUBEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForCUBEActionPerformed
        double t = Double.parseDouble(jTextField1.getText());

        t = t*t*t;
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonForCUBEActionPerformed

    private void jButtonForEQUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForEQUALActionPerformed
        num2 = Double.parseDouble(jTextField1.getText());

        if(opr == "+")
        {
            result = num1 + num2;
            jTextField1.setText(Double.toString(result));
        }

        else if(opr == "-")
        {
            result = num1 - num2;
            jTextField1.setText(Double.toString(result));
        }

        else if(opr == "*")
        {
            result = num1 * num2;
            jTextField1.setText(Double.toString(result));
        }

        else if(opr == "/")
        {
            result = num1/num2;
            jTextField1.setText(Double.toString(result));
        }

        else if(opr == "%")
        {
            result = num1 % num2;
            jTextField1.setText(Double.toString(result));
        }

        else if(opr == "x^y")
        {
            result = Math.pow(num1, num2);
            jTextField1.setText(Double.toString(result));
        }
    }//GEN-LAST:event_jButtonForEQUALActionPerformed

    private void jButtonForMULTIPICATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForMULTIPICATIONActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());

        jTextField1.setText("");
        opr = "*";
    }//GEN-LAST:event_jButtonForMULTIPICATIONActionPerformed

    private void jButtonFor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFor4ActionPerformed
        jTextField1.setText(jTextField1.getText() + "4");
    }//GEN-LAST:event_jButtonFor4ActionPerformed

    private void jButtonFor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFor5ActionPerformed
        jTextField1.setText(jTextField1.getText() + "5");
    }//GEN-LAST:event_jButtonFor5ActionPerformed

    private void jButtonFor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFor6ActionPerformed
        jTextField1.setText(jTextField1.getText() + "6");
    }//GEN-LAST:event_jButtonFor6ActionPerformed

    private void jButtonForMINUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForMINUSActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());

        jTextField1.setText("");
        opr = "-";
    }//GEN-LAST:event_jButtonForMINUSActionPerformed

    private void jButtonFor7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFor7ActionPerformed
        jTextField1.setText(jTextField1.getText() + "7");
    }//GEN-LAST:event_jButtonFor7ActionPerformed

    private void jButtonFor8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFor8ActionPerformed
        jTextField1.setText(jTextField1.getText() + "8");
    }//GEN-LAST:event_jButtonFor8ActionPerformed

    private void jButtonFor9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFor9ActionPerformed
        jTextField1.setText(jTextField1.getText() + "9");
    }//GEN-LAST:event_jButtonFor9ActionPerformed

    private void jButtonForPLUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForPLUSActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());

        jTextField1.setText("");
        opr = "+";
    }//GEN-LAST:event_jButtonForPLUSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScientificCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonFor0;
    private javax.swing.JButton jButtonFor1;
    private javax.swing.JButton jButtonFor2;
    private javax.swing.JButton jButtonFor3;
    private javax.swing.JButton jButtonFor4;
    private javax.swing.JButton jButtonFor5;
    private javax.swing.JButton jButtonFor6;
    private javax.swing.JButton jButtonFor7;
    private javax.swing.JButton jButtonFor8;
    private javax.swing.JButton jButtonFor9;
    private javax.swing.JButton jButtonForBACK;
    private javax.swing.JButton jButtonForCLR;
    private javax.swing.JButton jButtonForCOS;
    private javax.swing.JButton jButtonForCOSH;
    private javax.swing.JButton jButtonForCUBE;
    private javax.swing.JButton jButtonForDIVISION;
    private javax.swing.JButton jButtonForDOT;
    private javax.swing.JButton jButtonForEQUAL;
    private javax.swing.JButton jButtonForFACTORIAL;
    private javax.swing.JButton jButtonForLOG;
    private javax.swing.JButton jButtonForMINUS;
    private javax.swing.JButton jButtonForMODULAS;
    private javax.swing.JButton jButtonForMULTIPICATION;
    private javax.swing.JButton jButtonForPLUS;
    private javax.swing.JButton jButtonForROOT;
    private javax.swing.JButton jButtonForSIN;
    private javax.swing.JButton jButtonForSINH;
    private javax.swing.JButton jButtonForSQUARE;
    private javax.swing.JButton jButtonForTAN;
    private javax.swing.JButton jButtonForTANH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonForOFF;
    private javax.swing.JRadioButton jRadioButtonForON;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
